base:
  grades:
    1: 一年级
    2: 二年级
    3: 三年级
    4: 四年级
    5: 五年级
    6: 六年级
    7: 七年级
    8: 八年级
    9: 九年级
    10: 高一
    11: 高二
    12: 高三
  stages:
    1:
      stageId: 1
      stageName: 小学
      subjects:
        - subjectId: 1
          subjectName: 语文
        - subjectId: 2
          subjectName: 数学
        - subjectId: 3
          subjectName: 英语
        - subjectId: 7
          subjectName: 科学
        - subjectId: 8
          subjectName: 政治思品
    2:
      stageId: 2
      stageName: 初中
      subjects:
        - subjectId: 1
          subjectName: 语文
        - subjectId: 2
          subjectName: 数学
        - subjectId: 3
          subjectName: 英语
        - subjectId: 4
          subjectName: 物理
        - subjectId: 5
          subjectName: 化学
        - subjectId: 6
          subjectName: 生物
        - subjectId: 7
          subjectName: 科学
        - subjectId: 8
          subjectName: 政治思品
        - subjectId: 9
          subjectName: 历史
        - subjectId: 10
          subjectName: 地理
        - subjectId: 11
          subjectName: 历史与社会
        - subjectId: 12
          subjectName: 社会思品
    3:
      stageId: 3
      stageName: 高中
      subjects:
        - subjectId: 1
          subjectName: 语文
        - subjectId: 2
          subjectName: 数学
        - subjectId: 3
          subjectName: 英语
        - subjectId: 4
          subjectName: 物理
        - subjectId: 5
          subjectName: 化学
        - subjectId: 6
          subjectName: 生物
        - subjectId: 8
          subjectName: 政治思品
        - subjectId: 9
          subjectName: 历史
        - subjectId: 10
          subjectName: 地理
        - subjectId: 13
          subjectName: 信息技术
  plans:
    1:
      planId: 1
      planName: 小学五年制
      stageId: 1
      stageName: 小学
      grades:
        - gradeId: 1
          gradeName: 一年级
        - gradeId: 2
          gradeName: 二年级
        - gradeId: 3
          gradeName: 三年级
        - gradeId: 4
          gradeName: 四年级
        - gradeId: 5
          gradeName: 五年级
    2:
      planId: 2
      planName: 小学六年制
      stageId: 1
      stageName: 小学
      grades:
        - gradeId: 1
          gradeName: 一年级
        - gradeId: 2
          gradeName: 二年级
        - gradeId: 3
          gradeName: 三年级
        - gradeId: 4
          gradeName: 四年级
        - gradeId: 5
          gradeName: 五年级
        - gradeId: 6
          gradeName: 六年级
    3:
      planId: 3
      planName: 初中三年制
      stageId: 2
      stageName: 初中
      grades:
        - gradeId: 7
          gradeName: 七年级
        - gradeId: 8
          gradeName: 八年级
        - gradeId: 9
          gradeName: 九年级
    4:
      planId: 4
      planName: 初中四年制
      stageId: 2
      stageName: 初中
      grades:
        - gradeId: 6
          gradeName: 六年级
        - gradeId: 7
          gradeName: 七年级
        - gradeId: 8
          gradeName: 八年级
        - gradeId: 9
          gradeName: 九年级
    5:
      planId: 5
      planName: 高中
      stageId: 3
      stageName: 高中
      grades:
        - gradeId: 10
          gradeName: 高一
        - gradeId: 11
          gradeName: 高二
        - gradeId: 12
          gradeName: 高三
  subjects:
    1: 语文
    2: 数学
    3: 英语
    4: 物理
    5: 化学
    6: 生物
    7: 科学
    8: 政治思品
    9: 历史
    10: 地理
    11: 历史与社会
    12: 社会思品
    13: 信息技术
  roles:
    1: 学生
    2: 老师
    3: 班主任
    4: 教务
    5: 家长
    10: 学校财务
    11: 学校领导
    12: 年级组长
    13: 学科组长
    20: 教育局领导
    31: 平台教研员
    32: 平台管理员
