server:
  port: 0

management: 
  endpoint: 
    health: 
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: 192.168.10.140
    port: 5672
    username: ygxt
    password: ygyg2017
    listener:
      simple:
        retry:
          enabled: true
    template:
      retry:
        enabled: true
  redis:
    host: 192.168.10.140
    password: Password@1
  data:
    mongodb:
      uri: mongodb://ygxt:ygyg2017@192.168.10.140:27018/ygxt?authSource=admin
  datasource:
    url: jdbc:mysql://192.168.10.140/ygxt?useUnicode=true&ampcharacterEncoding=utf8&ampzeroDateTimeBehavior=convertToNull&ampuseSSL=false
    username: ygxt
    password: ygyg2017
    druid:
      initialSize: 1
      maxActive: 8
      minIdle: 1
      maxWait: 10000
      validationQuery: SELECT 1
      validationQueryTimeout: 5000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
ygxt:
  security:
    service:
      accessToken: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZXJ2aWNlIiwiZXhwIjoxNjg3NTkzNDU4LCJ1aWQiOjAsImtpZCI6MCwibmFtZSI6InNlcnZpY2UiLCJ0eXAiOiJhY2MiLCJwaWQiOiIiLCJyaWQiOjEwMCwiYXVzIjpbIlJPTEVfU0VSVklDRSJdLCJzaWQiOjB9.H0gdVaXcUmgsa3crQXjqbZaxwsc813b36-T8PzN9tFs
  swagger2:
    enable: true
    
fastdfs:
  tracker:
    uri: 192.168.10.140
    defaultGroup: group1
logging:
  path: log/
  level:
    io.swagger: ERROR


