server:
  port: 0

management:
  server:
    port: 0
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    include: base
#  servlet:
#    multipart:
#      location: /data/cloud/tmp
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.10.140:9411/
  rabbitmq:
    host: 192.168.31.235
    port: 5672
    username: ygxt
    password: 123456
    listener:
      simple:
        retry:
          enabled: true
    template:
      retry:
        enabled: true
  redis:
    host: 192.168.31.5
    password: 123321
  data:
    mongodb:
      uri: mongodb://192.168.31.104:27017/ygxt
      #uri: mongodb://admin:root@192.168.31.104:27017/ygxt
      #uri: mongodb://192.168.31.103:27017/ygxt
      #uri: mongodb://ygxt:ygyg2017@192.168.10.140:27018/ygxt?authSource=admin
  datasource:
    url: jdbc:mysql://192.168.31.5/ygxt?useUnicode=true&ampcharacterEncoding=utf8&ampzeroDateTimeBehavior=convertToNull&ampuseSSL=false
    #url: jdbc:mysql://192.168.10.140/ygxt?useUnicode=true&ampcharacterEncoding=utf8&ampzeroDateTimeBehavior=convertToNull&ampuseSSL=false
    username: root
    password: 123456
    druid:
      initialSize: 1
      maxActive: 8
      minIdle: 1
      maxWait: 10000
      validationQuery: SELECT 1
      validationQueryTimeout: 5000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
ygxt:
  feign:
    # 是否启用服务认证
    authAccessToken: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZXJ2aWNlIiwiZXhwIjoxNjg3NTkzNDU4LCJ1aWQiOjAsImtpZCI6MCwibmFtZSI6InNlcnZpY2UiLCJ0eXAiOiJhY2MiLCJwaWQiOiIiLCJyaWQiOjEwMCwiYXVzIjpbIlJPTEVfU0VSVklDRSJdLCJzaWQiOjB9.H0gdVaXcUmgsa3crQXjqbZaxwsc813b36-T8PzN9tFs
    # 是否启用远程调用异常解析
    parseRemoteError: true
  security:
    service:
      accessToken: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZXJ2aWNlIiwiZXhwIjoxNjg3NTkzNDU4LCJ1aWQiOjAsImtpZCI6MCwibmFtZSI6InNlcnZpY2UiLCJ0eXAiOiJhY2MiLCJwaWQiOiIiLCJyaWQiOjEwMCwiYXVzIjpbIlJPTEVfU0VSVklDRSJdLCJzaWQiOjB9.H0gdVaXcUmgsa3crQXjqbZaxwsc813b36-T8PzN9tFs
  swagger2:
    enable: true
    baseHost: api.yunguxt.com
    
fastdfs:
  tracker:
    uri: 192.168.94.130
    defaultGroup: group1
logging:
  path: log/
  level:
    io.swagger: ERROR

# hystrix超时时间要大于ribbon时间，否则ribbon超时直接熔断，重试机制无效, ribbon默认超时时间1000ms
# ribbonTimeout= (ribbonReadTimeout + ribbonConnectTimeout) *(maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1)
ribbon:
   ReadTimeout: 5000
   ConnectTimeout: 2000
   eager-load: true
   clients: user, work
hystrix:
  command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 16000
