server:
  port: 0
spring:
  rabbitmq:
    host: 192.168.10.140
    port: 5672
    username: ygxt
    password: ygyg2017
  redis:
    host: 192.168.10.140
    password: Password@1
  data:
    mongodb:
      uri: mongodb://ygxt:ygyg2017@192.168.10.140:27018/ygxt?authSource=admin
  datasource:
    url: jdbc:mysql://192.168.10.140/ygxt?useUnicode=true&ampcharacterEncoding=utf8&ampzeroDateTimeBehavior=convertToNull&ampuseSSL=false
    username: ygxt
    password: ygyg2017
    druid:
      initialSize: 1
      maxActive: 8
      minIdle: 1
      maxWait: 10000
      validationQuery: SELECT 1
      validationQueryTimeout: 5000
      testOnBorrow: true
      testOnReturn: false
      testWhileIdle: true
ygxt:
  swagger2:
    enable: true
    
fastdfs:
  tracker:
    uri: 192.168.10.140
    defaultGroup: group1
logging:
  path: log/

base:
  grades:
    1: 一年级
    2: 二年级
    3: 三年级
    4: 四年级
    5: 五年级
    6: 六年级
    7: 七年级
    8: 八年级
    9: 九年级
    10: 高一
    11: 高二
    12: 高三
  stages:
    1:
      stageId: 1
      stageName: 小学
      subjects:
        - subjectId: 1
          subjectName: 语文
        - subjectId: 2
          subjectName: 数学
        - subjectId: 3
          subjectName: 英语
    2:
      stageId: 2
      stageName: 中学
      subjects:
        - subjectId: 1
          subjectName: 语文
        - subjectId: 2
          subjectName: 数学
        - subjectId: 3
          subjectName: 英语
    3:
      stageId: 3
      stageName: 高中
      subjects:
        - subjectId: 1
          subjectName: 语文
        - subjectId: 2
          subjectName: 数学
        - subjectId: 3
          subjectName: 英语
  plans:
    1:
      planId: 1
      planName: 小学五年制
      stageId: 1
      stageName: 小学
      grades:
        - gradeId: 1
          gradeName: 一年级
        - gradeId: 2
          gradeName: 二年级
        - gradeId: 3
          gradeName: 三年级
        - gradeId: 4
          gradeName: 四年级
        - gradeId: 5
          gradeName: 五年级
    2:
      planId: 2
      planName: 小学六年制
      stageId: 1
      stageName: 小学
      grades:
        - gradeId: 1
          gradeName: 一年级
        - gradeId: 2
          gradeName: 二年级
        - gradeId: 3
          gradeName: 三年级
        - gradeId: 4
          gradeName: 四年级
        - gradeId: 5
          gradeName: 五年级
        - gradeId: 6
          gradeName: 六年级
    3:
      planId: 3
      planName: 中学三年制
      stageId: 2
      stageName: 中学
      grades:
        - gradeId: 7
          gradeName: 七年级
        - gradeId: 8
          gradeName: 八年级
        - gradeId: 9
          gradeName: 九年级
    4:
      planId: 4
      planName: 中学四年制
      stageId: 2
      stageName: 中学
      grades:
        - gradeId: 6
          gradeName: 六年级
        - gradeId: 7
          gradeName: 七年级
        - gradeId: 8
          gradeName: 八年级
        - gradeId: 9
          gradeName: 九年级
    5:
      planId: 5
      planName: 高中
      stageId: 3
      stageName: 高中
      grades:
        - gradeId: 10
          gradeName: 高一
        - gradeId: 11
          gradeName: 高二
        - gradeId: 12
          gradeName: 高三
  subjects:
    1: 语文
    2: 数学
    3: 英语
  roles:
    1: 学生
    2: 老师
    3: 班主任
    4: 教务
    5: 家长
    10: 学校财务
    11: 学校领导
    12: 年级组长
    13: 学科组长
    20: 教育局领导
