server:
  port: 6017
spring:
  data:
    mongodb:
      uri: mongodb://ygxt:ygyg2017@192.168.10.140:27018/chat?authSource=admin
ygxt:
  chat:
    instanceId: ${spring.cloud.client.hostname}
  socket:
    impl: vertx
    port: 8888
    executor:
      corePoolSize: 1
      maxPoolSize: 50
      keepAliveSeconds: 60
  getui:
    enable: true
    appId: U1v0pvroqg9yUej2ZBGAT5
    appKey: wwTmgJlXkm6098pc7BwnN1
    appSecret: HQpAo1x3o4AIk0wmZRUlW8
    masterSecret: W9XYBawQANA934x4HKfML
    appHost: http://sdk.open.api.igexin.com/apiex.htm