server:
  port: 5001
spring:
  application:
    name: ygxt-cloud-registry
eureka:
  instance:
    hostname: registry
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/