server:
  port: 6014
management:
  server:
    port: 7014
spring:
  data:
    mongodb:
      #uri: mongodb://ygxt:ygyg2017@192.168.10.140:27018/lesson?authSource=admin
      uri: mongodb://192.168.31.5:27017/admin
      #uri: mongodb://localhost:27017/ygxt
  rabbitmq:
    listener:
      simple:
        concurrency: 10
