server:
  port: 6016
management:
  server:
    port: 7016
spring:
  data:
    mongodb:
      #uri: mongodb://ygxt:ygyg2017@192.168.10.140:27018/lesson?authSource=admin
       uri: mongodb://192.168.31.5:27017/admin
      #uri: mongodb://localhost:27017/ygxt
ygxt:
  record:
    instanceId: ${spring.cloud.client.hostname}
