server:
  port: 6016
spring:
  data:
    mongodb:
      uri: mongodb://ygxt:ygyg2017@192.168.10.140:27018/lesson?authSource=admin
ygxt:
  record:
    instanceId: ${spring.cloud.client.hostname}
