spring:
  application:
    name: repository
  data:
    mongodb:
      uri: mongodb://ygxt:ygyg2017@192.168.10.140:27018/ygxt?authSource=admin
server:
  port: 8202
ygxt:
  swagger2:
    enable: true
    code: repository
