spring:
  application:
    name: repository
  data:
    mongodb:
      uri: mongodb://ygxt:ygyg2017@192.168.10.140:27018/ygxt?authSource=admin
      # uri: mongodb://127.0.0.1/ygxt
server:
  port: 8202
ygxt:
  swagger2:
    enable: true
    code: repository
