server:
    port: 6010
management:
  server:
    port: 6899
spring:
  servlet:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 10Mb
elasticsearch:
  #hosts: http://192.168.10.140:9200
   hosts: http://122.112.231.159:9200
